global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dns'
    static_configs:
    - targets: ['dns:4000']
      labels:
        instance: 'vmk-srv-01'

  - job_name: 'traefik'
    static_configs:
    - targets: ['proxy:8080']
      labels:
        instance: 'vmk-srv-01'

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
      labels:
        instance: 'vmk-srv-01'

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
      labels:
        instance: 'vmk-srv-01'
  
  - job_name: 'http_proxy'
    static_configs:
    - targets: ['squid_proxy_exporter.internal:9301']
      labels:
        instance: 'vmk-srv-01'

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['10.10.2.8:9100']
      labels:
        instance: 'vmk-srv-01'
